import Head from 'next/head';
import { useState } from 'react';
import ContactMe from '../components/ContactMe';
import Portfolio from '../components/Portfolio';
import ReachOut from '@/components/ReachOut';
import About from '@/components/About';
import Skills from '@/components/Skills';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Raimy Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-white dark:bg-gray-900 pb-10'>
        <About darkMode={darkMode} setDarkMode={setDarkMode} />
        <Portfolio />
        <Skills />
        <ContactMe />
        <ReachOut />
      </main>
    </div>
  );
}
